services:
  - type: web
    name: co-pay-api
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
